sudo: required
services:
  - docker

before_install:
  - docker build -t zenakent/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zenakent/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  #http://dockerreact-env.eba-nguzypww.us-east-2.elasticbeanstalk.com/
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk_us-east-2-159843824656"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
